# -*- coding: utf-8 -*-
"""Alterno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvi_VpyUhdYtpxI8dBBWBOycxVrVxo96
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# -----------------------------------------------------
# CONFIG
# -----------------------------------------------------
st.set_page_config(page_title="Modelo Hooke Trading", layout="wide")

TICKERS = ["BTC-USD","FMTY14.MX","GMEXICOB.MX","GENTERA.MX","AMZN","MELI","JPM","V","CHDRAUIB.MX","SOFI","AMD","GAPB.MX","PINFRA.MX","NFLX","GOOGL","MCD","PLTR","SPY","IAU","HOOD","NVDA","WALMEX.MX","FUNO11.MX","QBTS","QUBT","QTUM","FRES.MX","MCHI","INDA","TSM","ASURB.MX","ZC=F","HG=F","BZ=F","^MOVE","^VIX","DX-Y.NYB"]

st.title("Modelo del Resorte de Hooke aplicado al Trading")

# -----------------------------------------------------
# FUNCIÓN ROBUSTA 🔥
# -----------------------------------------------------
def get_clean_data(ticker, period="2y"):
    df = yf.download(ticker, period=period, interval="1d")

    if df.empty:
        return None

    df = df.copy()

    # 🔥 Manejo de MultiIndex (muy común en yfinance)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    # 🔥 Asegurar columnas clave
    required_cols = ["Close"]
    for col in required_cols:
        if col not in df.columns:
            return None

    # 🔥 Convertir a float seguro
    if isinstance(df["Close"], pd.DataFrame):
        df["Close"] = df["Close"].iloc[:, 0]

    df["Close"] = pd.to_numeric(df["Close"], errors="coerce")

    df.dropna(inplace=True)

    return df

# -----------------------------------------------------
# SELECCIÓN
# -----------------------------------------------------
ticker = st.selectbox("Selecciona un activo:", TICKERS)
st.write(f"Descargando datos de **{ticker}**...")

df = get_clean_data(ticker)

if df is None or df.empty:
    st.error("No se pudieron procesar los datos.")
    st.stop()

# -----------------------------------------------------
# INDICADORES
# -----------------------------------------------------
df["MA5"] = df["Close"].rolling(5).mean()
df["MA10"] = df["Close"].rolling(10).mean()
df.dropna(inplace=True)

df["Signal"] = np.where(df["MA5"] > df["MA10"], 1, 0)
df["Crossover"] = df["Signal"].diff()

# -----------------------------------------------------
# MODELO HOOKE
# -----------------------------------------------------
df["x"] = df["Close"] - df["MA10"]
k = 0.001
df["Force"] = -k * df["x"]

threshold = df["x"].std() * 1.5
df["Exit"] = np.where(abs(df["x"]) > threshold, 1, 0)
df["Exit_diff"] = df["Exit"].diff().fillna(0)

# -----------------------------------------------------
# FECHAS NUMÉRICAS (CLAVE)
# -----------------------------------------------------
x_dates = mdates.date2num(df.index)

# -----------------------------------------------------
# GRÁFICO
# -----------------------------------------------------
fig, ax1 = plt.subplots(figsize=(14, 7))

ax1.plot(x_dates, df["Close"], label="Precio", color="black")
ax1.plot(x_dates, df["MA10"], label="Media móvil", color="orange")

# Último punto
ax1.scatter(
    x_dates[-1],
    float(df["Close"].iloc[-1]),
    color='red',
    s=40,
    zorder=5,
    label="Último valor"
)

# Zona elástica
ax1.fill_between(
    x_dates,
    (df["MA10"] - threshold).astype(float),
    (df["MA10"] + threshold).astype(float),
    color="green",
    alpha=0.2,
    label="Zona elástica"
)

# Señales
y_max = float(df["Close"].max())
y_min = float(df["Close"].min())

exit_dates = df[(df["Exit_diff"] == 1) & (df["MA5"] > df["MA10"])].index
entry_dates = df[(df["Exit_diff"] == -1) & (df["MA5"] < df["MA10"])].index

for date in exit_dates:
    x = mdates.date2num(date)
    ax1.axvline(x=x, color="red", linestyle="--", alpha=0.5)
    ax1.text(x, y_max, "S", color="red", fontsize=8, rotation=90, va="top")

for date in entry_dates:
    x = mdates.date2num(date)
    ax1.axvline(x=x, color="green", linestyle="--", alpha=0.5)
    ax1.text(x, y_min, "E", color="green", fontsize=8, rotation=90, va="bottom")

ax1.xaxis_date()

ax1.set_xlabel("Fecha")
ax1.set_ylabel("Precio")
ax1.grid(True)
ax1.legend(loc="upper left")

# Fuerza
ax2 = ax1.twinx()
ax2.plot(x_dates, df["Force"], label="Fuerza (-k*x)", color="blue", linestyle="--")
ax2.set_ylabel("Fuerza")
ax2.legend(loc="lower left")

plt.title(f"Modelo de Hooke aplicado a {ticker}")

# 🔥 YA NO FALLA
st.pyplot(fig)

# -----------------------------------------------------
# MÉTRICAS
# -----------------------------------------------------
precio = float(df["Close"].iloc[-1])
st.metric("Precio actual", f"{precio:.2f}")

# -----------------------------------------------------
# RETORNO
# -----------------------------------------------------
df1 = get_clean_data(ticker, period="1y")

if df1 is not None and not df1.empty:
    r = ((df1["Close"].iloc[-1] - df1["Close"].iloc[0]) / df1["Close"].iloc[0]) * 100
    st.metric("Rendimiento 1Y", f"{r:.2f}%")

    # -----------------------------------------------------
    # HISTOGRAMA
    # -----------------------------------------------------
    precios = df1["Close"].values

    n = len(precios)
    k = int(1 + np.log2(n))

    bins = np.linspace(min(precios), max(precios), k)

    precios_categorizados = pd.cut(precios, bins=bins, right=False)

    tabla_frecuencias = precios_categorizados.value_counts().sort_index()
    frecuencia_relativa = tabla_frecuencias / n

    df3 = pd.DataFrame({
        'Intervalo': [str(interval) for interval in tabla_frecuencias.index],
        'Frecuencia Relativa': frecuencia_relativa.values
    }).sort_values(by='Frecuencia Relativa', ascending=False)

    st.dataframe(df3)

# -----------------------------------------------------
# ESTILO
# -----------------------------------------------------
st.markdown("""
<style>
    .stApp {
        background-color: #00FF00;
    }
</style>
""", unsafe_allow_html=True)
